spring:
# DataSource
  datasource:
    url: jdbc:mysql://localhost:3306/booksDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
# Thymeleaf
  thymeleaf:
    prefix: classpath:/templates
    cache: false
    mode: HTML
